[CmdletBinding()]
param(
  [string]$Root,
  [string]$DemoDir
)

$ErrorActionPreference = "Stop"

$scriptBase = $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($scriptBase)) {
  $scriptBase = (Get-Location).Path
}

if ([string]::IsNullOrWhiteSpace($Root)) {
  $Root = (Resolve-Path (Join-Path $scriptBase "..")).Path
}

if ([string]::IsNullOrWhiteSpace($DemoDir)) {
  $DemoDir = Join-Path $Root "azure-demo"
}

$rootEnvLocal = Join-Path $Root ".env.local"
$rootEnv = Join-Path $Root ".env"
$outEnvLocal = Join-Path $DemoDir ".env.local"

if (-not (Test-Path $DemoDir)) {
  throw "Demo folder not found: $DemoDir"
}

function Read-DotEnvFile([string]$path) {
  if (-not (Test-Path $path)) { return @{} }

  $map = @{}
  $lines = Get-Content -LiteralPath $path -ErrorAction Stop

  foreach ($line in $lines) {
    $trim = $line.Trim()
    if ($trim.Length -eq 0) { continue }
    if ($trim.StartsWith("#")) { continue }

    $idx = $trim.IndexOf("=")
    if ($idx -lt 1) { continue }

    $key = $trim.Substring(0, $idx).Trim()
    $val = $trim.Substring($idx + 1)

    # Strip optional surrounding quotes
    if (($val.StartsWith('"') -and $val.EndsWith('"')) -or ($val.StartsWith("'") -and $val.EndsWith("'"))) {
      $val = $val.Substring(1, $val.Length - 2)
    }

    $map[$key] = $val
  }

  return $map
}

# Precedence: .env.local overrides .env
$root = Read-DotEnvFile $rootEnv
$rootLocal = Read-DotEnvFile $rootEnvLocal
$merged = @{}
foreach ($k in $root.Keys) { $merged[$k] = $root[$k] }
foreach ($k in $rootLocal.Keys) { $merged[$k] = $rootLocal[$k] }

$keys = @(
  "DEMO_USE_AZURE_OPENAI",
  "AZURE_OPENAI_ENDPOINT",
  "AZURE_OPENAI_API_KEY",
  "AZURE_OPENAI_MODEL_DEPLOYMENT",
  "AZURE_OPENAI_DEPLOYMENT",
  "AZURE_OPENAI_API_VERSION",
  "DEMO_USE_DOCUMENT_INTELLIGENCE",
  "AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT",
  "AZURE_DOCUMENT_INTELLIGENCE_API_KEY",
  "AZURE_DOCUMENT_INTELLIGENCE_API_VERSION"
)

$linesOut = New-Object System.Collections.Generic.List[string]
$linesOut.Add("# Auto-generated by scripts/sync-azure-demo-env.ps1")
$linesOut.Add("# Source: Agentic-E-Commerce-Platform/.env + .env.local")
$linesOut.Add("")

foreach ($k in $keys) {
  if ($merged.ContainsKey($k) -and $null -ne $merged[$k] -and $merged[$k].Length -gt 0) {
    $v = $merged[$k]

    # Escape only if needed.
    $needsQuotes = ($v -match "\s") -or $v.Contains('"') -or $v.Contains("'")
    if ($needsQuotes) {
          $vEscaped = $v.Replace('"', '\"')
      $linesOut.Add("$k=`"$vEscaped`"")
    } else {
      $linesOut.Add("$k=$v")
    }
  }
}

# Helpful compat: if MODEL_DEPLOYMENT exists but DEPLOYMENT missing, copy it.
if ($merged.ContainsKey("AZURE_OPENAI_MODEL_DEPLOYMENT") -and -not $merged.ContainsKey("AZURE_OPENAI_DEPLOYMENT")) {
  $linesOut.Add("AZURE_OPENAI_DEPLOYMENT=$($merged['AZURE_OPENAI_MODEL_DEPLOYMENT'])")
}

Set-Content -LiteralPath $outEnvLocal -Value $linesOut -Encoding UTF8

Write-Host "Wrote $outEnvLocal"